INSERT INTO `utente` (`idutente`, `username`, `email`, `password`, `foto profilo`) VALUES
(1, 'mastercast', 'magnasas@sassezza.com', '$2y$10$KJE6fjPZZkIL9oImmiC2JuNAL1v0noDZBspzU7kJpso9tpWRcbLeS', 'fotoprofilo1.PNG'),
(2, 'Amogus', 'SussyBaka@SussyBukky.com', '$2y$10$YBcv4M6kUYbBDlPpPfuA5uiLC6rfRp2B1OPCBgcFXq70OOa9G9GOO', 'fotoprofilo2.PNG');

INSERT INTO `post` (`idpost`, `testo`, `immagine`, `autore`, `data`) VALUES
(1, 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut tenetur quos nostrum, nisi doloribus maiores eum delectus dolorum corrupti facilis qui iste ea minima, vero libero quia accusantium numquam placeat!', NULL, 1, '2023-01-24 15:30:27'),
(2, 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut tenetur quos nostrum, nisi doloribus maiores eum delectus dolorum corrupti facilis qui iste ea minima, vero libero quia accusantium numquam placeat!', 'mood.png', 1, '2023-01-23 23:14:11'),
(3, 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut tenetur quos nostrum, nisi doloribus maiores eum delectus dolorum corrupti facilis qui iste ea minima, vero libero quia accusantium numquam placeat!', 'PogAinsley.jpg', 1, '2022-11-15 09:26:01'),
(4, 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut tenetur quos nostrum, nisi doloribus maiores eum delectus dolorum corrupti facilis qui iste ea minima, vero libero quia accusantium numquam placeat!', 'PogAinsley.jpg', 2, '2023-01-01 05:30:55'),
(5, 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut tenetur quos nostrum, nisi doloribus maiores eum delectus dolorum corrupti facilis qui iste ea minima, vero libero quia accusantium numquam placeat!', 'PogAinsley.jpg', 2, '2023-01-21 17:21:45'),
(6, 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ut tenetur quos nostrum, nisi doloribus maiores eum delectus dolorum corrupti facilis qui iste ea minima, vero libero quia accusantium numquam placeat!', NULL, 2, '2023-01-23 01:45:46');

INSERT INTO `film` (`idfilm`, `nome`, `durata`, `trama`, `immagine`) VALUES
(1, "Ready Player One", 140, "Nell'anno 2045 l'inquinamento e la sovrappopolazione hanno rovinato la vita sulla Terra e molte delle sue città sono diventate baraccopoli. Come via di fuga dalle loro vite nelle città decadenti, le persone si immergono nel mondo virtuale di OASIS (acronimo di Ontologically Anthropocentric Sensory Immersive Simulation), dove possono prendere parte a numerose attività per lavoro, istruzione e intrattenimento. Quando il suo co-fondatore e creatore James Halliday muore, annuncia tramite il suo avatar 'Anorak l'Onnisciente' un concorso in cui i giocatori devono trovare un easter egg all'interno del mondo di gioco, ma per sbloccarlo servono tre chiavi nascoste in tre diverse sfide sconosciute. Il vincitore riceverà il controllo totale di OASIS (valutato oltre mezzo bilione di dollari). Questo attira un certo numero di Gunters (da egg hunters, 'cacciatori di uova') e la multinazionale Innovative Online Industries (IOI), guidata dal nuovo CEO Nolan Sorrento, che impiega i migliori giocatori, i ricercatori di Halliday e i dipendenti a contratto chiamati 'Sixers' allo scopo di vincere la gara e privatizzare OASIS.", "RPO.jpg"),
(2, "Harry Potter e la pietra filosofale", 159, "Harry Potter, rimasto orfano dei genitori, James Potter e Lily Evans, all'età di un anno, viene lasciato dai professori della Scuola di Magia e Stregoneria di Hogwarts, Albus Silente (preside della scuola) e Minerva McGranitt, e dal guardiacaccia della scuola, Rubeus Hagrid, davanti alla dimora degli zii materni, Vernon e Petunia Dursley, e del cugino Dudley, sulla strada di Privet Drive. Nei successivi dieci anni, Harry cresce in un clima ostile, trattato come un estraneo a causa dell'odio e dell'invidia che la zia Petunia provava nei confronti della sorella e costretto a dormire nello sgabuzzino sotto le scale. Presto, però, Harry si rende conto di essere in grado di fare cose incredibili, come quando, con tutta la famiglia, fa visita allo zoo nel giorno del compleanno di Dudley e, mentre guarda un pitone, Harry riesce a dialogare con lui e a far sparire il vetro della teca che lo rinchiude, facendo cadere al suo interno il cugino e liberando il serpente dalla sua prigionia.", "HPELPF.jpg"),
(3, "Il Signore degli Anelli - Le due torri", 235, "Durante la marcia verso Mordor, Frodo e Sam si accorgono di essere seguiti e tendono una trappola al loro inseguitore, Gollum, catturandolo e a strappandogli la promessa di essere accompagnati a Mordor in cambio della libertà. A Isengard, Saruman crea sempre più Uruk-hai per la guerra contro Rohan e si allea con gli uomini delle montagne. In uno scontro con le forze di Saruman, Théodred, figlio del re Théoden, rimane gravemente ferito, per poi essere ritrovato dal cugino Éomer, in fin di vita, e condotto a Edoras. Qui Éomer è bandito da Rohan, dopo uno scontro verbale con Grima Vermilinguo, in cui il nipote del Re manifesta i suoi sospetti verso di lui: infatti, in segreto, Grima lavora per Saruman e ritiene pericolosa la presenza di Éomer. La cacciata di Éomer lascia la sorella di quest'ultimo, Éowyn, inerme e indifesa alle trame del viscido consigliere dello zio.", "SDALDT.jpg"),
(4, "Interstellar", 169, "Nel 2067, l'ex pilota della NASA Cooper è costretto a lavorare come agricoltore a causa di una carestia globale causata dalla peronospora. La carestia è abbastanza grave da aver avuto effetti importanti sulla società umana, compreso l'abbandono di qualsiasi ricerca scientifica che non sia direttamente correlata alla soluzione del problema alimentare mondiale. Le scuole governative scoraggiano attivamente gli allievi dallo studiare materie come l'esplorazione spaziale, sostenendo che eventi storici come lo sbarco sulla luna siano una bufala politica e che organizzazioni scientifiche come la NASA siano state chiuse a causa della convinzione che fossero uno spreco di denaro e risorse.", "Interstellar.jpg"),
(5, "Star Wars: L'ascesa di Skywalker", 142, "Circa un anno dopo gli eventi de Gli ultimi Jedi, Rey si sta allenando sotto la guida del generale Leia Organa, per completare la sua istruzione di Jedi. Nel frattempo, su Mustafar, il nuovo Leader Supremo Kylo Ren ottiene un dispositivo che gli consente di raggiungere Exegol, un pianeta nascosto nelle Regioni Ignote dove da tempo si nasconde l'Imperatore Palpatine, ritornato grazie al lato oscuro della Forza. Costui, che rivela essere il creatore del personaggio di Snoke, ha preparato un'immensa flotta di incrociatori stellari, ciascuno dotato di un'arma in grado di distruggere un pianeta, con la quale intende invadere la galassia e ripristinare il defunto Impero Galattico. Palpatine promette a Ren di fornirgli la flotta per farlo diventare il nuovo Imperatore, ma a condizione che uccida Rey.", "SWTRS.jpg");

INSERT INTO `serietv` (`idserietv`, `nome`, `stagioni`, `episodi`, `durata episodi`, `trama`, `immagine`) VALUES
(1, 'The Office', 9, 204, 42, "La serie inizia presentando i dipendenti della Dunder Mifflin tramite un tour offerto dal direttore di filiale Michael Scott, sia per una troupe di documentari che per il primo giorno di Ryan Howard. Il pubblico apprende che il venditore Jim Halpert ha una cotta per la receptionist Pam Beesly, che lo aiuta a fare scherzi al collega Dwight Schrute, anche se è fidanzata con Roy, che lavora nel magazzino al piano di sotto dell'azienda. In tutto l'ufficio si è sparsa la voce che la sede centrale della Dunder Mifflin stia pianificando di ridimensionare un'intera filiale, generando ansia generale, ma Michael sceglie di negare o minimizzare la realtà della situazione per mantenere alto il morale dei dipendenti.", "TheOffice.jpg"),
(2, 'The Big Bang Theory', 12, 279, 20, "Pasadena. Leonard, Sheldon, Howard e Raj sono quattro giovani che lavorano al California Institute of Technology. La grande intelligenza ne fa tra le menti più valide del Paese, ma di contro li rende socialmente inadeguati: il loro legame d'amicizia è infatti cementato dalla rispettiva condizione di nerd e geek. Fuori dal lavoro il tempo libero dei quattro trascorre principalmente tra la lettura di fumetti, partite a videogame e giochi di ruolo, e la visione di film e serie TV di fantascienza e supereroi; l'assenza di ragazze è sempre stata una costante nelle loro vite. Questa routine cambia radicalmente quando Penny, una ragazza di provincia giunta in California per tentare la carriera di attrice, diventa la nuova vicina di pianerottolo di Sheldon e Leonard. La ragazza, bella ed esuberante, e della quale Leonard s'innamora a prima vista, è l'esatto opposto dei quattro amici; lo strano e complicato mondo dei ragazzi finisce ben presto per scontrarsi con quello semplice e superficiale di Penny, e le loro tranquille esistenze ne risultano inevitabilmente stravolte. Con il passare degli anni il gruppo si allarga a quelle che diventeranno le migliori amiche di Penny, Bernadette e Amy, due brillanti scienziate nonché destinate a diventare l'interesse amoroso, rispettivamente, di Howard e Sheldon, oltre a Stuart, titolare della fumetteria frequentata dai quattro amici.", "TBBT.jpg"),
(3, 'Friends', 10, 236, 22, "Rachel Green ha appena lasciato all'altare il suo futuro marito quando reincontra la sua vecchia amica del liceo Monica, ora una chef newyorkese. Diventate presto coinquiline, Rachel si unisce al gruppo di amici di Monica: il mediocre attore italoamericano Joey, l'analista contabile Chandler, la massaggiatrice e musicista a tempo perso Phoebe, e il paleontologo Ross (appena divorziato dalla moglie scopertasi lesbica), fratello maggiore di Monica. Per vivere, Rachel inizia a lavorare come cameriera al Central Perk, una caffetteria punto di ritrovo degli amici; quando non sono al caffè, i sei sono spesso all'appartamento di Monica e Rachel, situato a West Village, parte di Manhattan, o a quello di Joey e Chandler, che si trova esattamente di fronte.", "Friends.jpg"),
(4, 'Il Trono di Spade', 8, 73, 81, "Eddard Stark, lord di Grande Inverno, viene incaricato dal suo re e amico, Robert Baratheon, di recarsi ad Approdo del Re per ricoprire la carica di Primo Cavaliere del Re. La guerra fra i Sette Regni è però alle porte a causa degli intrighi e delle mire al Trono di Spade dei membri della nobile Casa Lannister. Jon Snow, figlio illegittimo di Eddard Stark, si arruola invece nei Guardiani della notte e si reca alla Barriera, enorme muro di ghiaccio che separa il mondo degli uomini dalle ostili Terre dell'Eterno Inverno, da cui sta arrivando una minaccia terribile. Nel frattempo, Daenerys Targaryen e il suo crudele fratello maggiore, Viserys, ultimi superstiti della nobile Casa Targaryen regnante prima della rivolta dei Baratheon, cercano di ricostruire il loro antico potere nelle selvagge terre al di là del mare.", "GOT.jpg"),
(5, 'Breaking Bad', 5, 62, 58, "Walter White è un professore di chimica di Albuquerque, New Mexico, che vive con la moglie Skyler, incinta della loro secondogenita, e il figlio Walter 'Flynn' Junior, affetto da una paralisi cerebrale che gli causa problemi di linguaggio e lo costringe a camminare con l'aiuto di stampelle per muoversi. Alla soglia dei cinquant'anni scopre di avere un tumore e per far fronte alle difficoltà economiche della famiglia, Walter è costretto a svolgere un secondo lavoro come dipendente di un autolavaggio. A tutto questo si aggiunge il profondo senso di insoddisfazione di Walter, che deve sopportare le angherie del suo titolare, dei suoi amici e familiari, i quali lo vedono come un uomo debole e remissivo. In particolare suo cognato Hank, agente della DEA, con cui peraltro ha un buon rapporto, non perde occasione per mettere a confronto la sua vita avventurosa con quella di Walter, totalmente priva di soddisfazioni.", "BBad.jpg");

INSERT INTO `anime` (`idanime`, `nome`, `stagioni`, `episodi`, `durata episodi`, `trama`, `immagine`) VALUES
(1, 'Dr.Stone', 2, 24, 23, "Anno 5738: da migliaia di anni l'intera umanità si ritrova tramutata in pietra a causa di una catastrofe naturale. Ooki Taiju riesce inspiegabilmente a risvegliarsi, trovandosi così di fronte ad una realtà completamente diversa da quanto ricordava, dove la natura ha ripreso il sopravvento sulla civiltà umana. Al suo risveglio il ragazzo si ricongiunge con il suo amico Senkuu, un giovane e geniale scienziato anche lui risvegliatosi qualche mese prima. Insieme i ragazzi sperano di scoprire la causa dietro all'improvvisa tramutazione in pietra - e, nel frattempo, di trovare una cura. Non tutto, però, va come previsto...", "DrStone.jpg"),
(2, 'Vinland Saga', 1, 24, 24, "Europa, Undicesimo Secolo. I popoli vichinghi sono ormai una forza inarrestabile e nessuna costa del continente può dirsi al sicuro dalle navi con la prua di drago. Inizia l'epica narrazione di Vinland Saga, in cui si intrecciano la Grande Storia e le vicende personali di un gruppo di personaggi come il giovane Thorfinn, il cui unico scopo è placare la sua sete di vendetta, e Askeladd, astuto capo di una torma di vichinghi.", "VinlandSaga.jpg"),
(3, 'Spy x Family', 2, 24, 25, "Twilight, una delle migliori spie al mondo, ha trascorso la vita ad affrontare missioni sotto copertura per rendere il mondo un posto migliore. Un giorno però riceve un compito particolarmente difficile, per riuscire nella sua nuova missione dovrà formare una famiglia temporanea e iniziare una nuova vita!", "SpyxFamily.png"),
(4, 'Tensei shitara Ken Deshita', 1, 12, 24, "Il protagonista si ritrova in un altro mondo e realizza di essere diventato una spada, conficcata in una vasta pianura infestata da bestie. Questo mondo ha un sistema simile a quello di un videogame: HP, MP, forza, agilità, destrezza, equipaggiamenti. Seguendo il suo istinto di spada senziente, viaggia in cerca di una persona degna di brandirla, e finisce così nelle mani di una ragazza-gatto in pericolo.", "SpadaParla.jpg"),
(5, 'Cyberpunk: Edgerunners', 1, 10, 25, "Storia indipendente di 10 episodi ambientata nello stesso universo di Cyberpunk 2077, videogioco open-world d'azione sviluppato da CD PROJEKT RED. Protagonista è uno 'street kid' che cerca di sopravvivere in una città ossessionata dalla tecnologia e dalle modifiche corporee. Avendo tutto da perdere, sceglie di diventare un 'edgerunner', ossia un mercenario fuorilegge anche noto come 'cyberpunk'.", "Depression.jpg");

INSERT INTO `content_seguito` (`idutente`, `idfilm`, `idserietv`, `idanime`, `notifiche`) VALUES
(1, NULL, 5, NULL, 1);

INSERT INTO `post_associati` (`idpost`, `idfilm`, `idserietv`, `idanime`) VALUES
(2, NULL, 5, NULL);

INSERT INTO `utente_seguito` (`idutente`, `idutenteseguito`) VALUES
(1, 2),
(2, 1);